import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useContext, useState, useEffect } from 'react';
import { AppContext } from '../App';
import { Link } from 'react-router-dom';
import { MapPin, ArrowRight, Search, ChevronLeft, ChevronRight, Star, Sparkles } from 'lucide-react';
const ExhibitionSlider = ({ museums }) => {
    const [current, setCurrent] = useState(0);
    const { language, uiLabels: labels } = useContext(AppContext);
    // Auto-play
    useEffect(() => {
        const timer = setInterval(() => {
            setCurrent((prev) => (prev === museums.length - 1 ? 0 : prev + 1));
        }, 6000);
        return () => clearInterval(timer);
    }, [museums.length]);
    const prev = () => setCurrent((curr) => (curr === 0 ? museums.length - 1 : curr - 1));
    const next = () => setCurrent((curr) => (curr === museums.length - 1 ? 0 : curr + 1));
    if (!museums.length)
        return null;
    return (_jsx("section", {
        className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-20 mb-20 relative z-30", children: _jsx("div", {
            className: "bg-slate-800/40 backdrop-blur-xl rounded-3xl border border-white/10 p-2 shadow-2xl hover:shadow-amber-900/10 transition-shadow duration-500", children: _jsxs("div", {
                className: "relative h-[450px] md:h-[500px] rounded-2xl overflow-hidden group", children: [museums.map((museum, index) => {
                    const exhibition = museum.highlights[0];
                    const bgImage = (museum.galleryImages && museum.galleryImages.length > 0)
                        ? museum.galleryImages[0].url
                        : museum.image;
                    // Localized Content
                    const exhibitionTitle = exhibition?.title[language];
                    const exhibitionDesc = exhibition?.description[language];
                    return (_jsxs("div", { className: `absolute inset-0 transition-all duration-1000 ease-in-out ${index === current ? 'opacity-100 scale-100 z-10' : 'opacity-0 scale-105 z-0'}`, children: [_jsx("img", { src: bgImage, alt: exhibitionTitle, className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-900/60 to-transparent" }), _jsx("div", { className: "absolute bottom-0 left-0 w-full p-8 md:p-16 flex flex-col justify-end h-full", children: _jsxs("div", { className: `transform transition-all duration-700 delay-200 ${index === current ? 'translate-y-0 opacity-100' : 'translate-y-8 opacity-0'}`, children: [_jsx("div", { className: "flex items-center gap-2 mb-4", children: _jsxs("span", { className: "inline-flex items-center gap-1 px-3 py-1 bg-amber-500/90 backdrop-blur-md text-slate-950 text-xs font-bold rounded-full uppercase tracking-wider shadow-[0_0_15px_rgba(245,158,11,0.4)]", children: [_jsx(Star, { size: 12, fill: "currentColor" }), "Featured Exhibition"] }) }), _jsx("h3", { className: "text-3xl md:text-5xl font-bold text-white mb-4 leading-tight max-w-4xl drop-shadow-lg", children: exhibitionTitle }), _jsx("p", { className: "text-lg md:text-xl text-slate-200 mb-8 max-w-2xl line-clamp-2 md:line-clamp-none drop-shadow-md", children: exhibitionDesc }), _jsx("div", { className: "flex flex-wrap items-center gap-6", children: _jsxs(Link, { to: `/museum/${museum.id}`, className: "group/btn bg-white/10 hover:bg-amber-500 hover:text-slate-900 text-white border border-white/30 hover:border-amber-500 px-8 py-3 rounded-full font-bold transition-all duration-300 backdrop-blur-sm flex items-center gap-2 hover:shadow-[0_0_20px_rgba(245,158,11,0.4)]", children: [labels.readMore, _jsx(ArrowRight, { size: 18, className: "group-hover/btn:translate-x-1 transition-transform" })] }) })] }) })] }, museum.id));
                }), _jsxs("div", { className: "absolute bottom-8 right-8 z-20 flex gap-3", children: [_jsx("button", { onClick: prev, className: "bg-black/30 hover:bg-amber-500 hover:text-slate-900 text-white p-3 rounded-full backdrop-blur-md transition-all border border-white/10 hover:scale-110 active:scale-95", children: _jsx(ChevronLeft, { size: 24 }) }), _jsx("button", { onClick: next, className: "bg-black/30 hover:bg-amber-500 hover:text-slate-900 text-white p-3 rounded-full backdrop-blur-md transition-all border border-white/10 hover:scale-110 active:scale-95", children: _jsx(ChevronRight, { size: 24 }) })] }), _jsx("div", { className: "absolute bottom-0 left-0 w-full flex", children: museums.map((_, idx) => (_jsx("div", { className: `h-1 transition-all duration-500 ${idx === current ? 'flex-1 bg-amber-500 shadow-[0_0_10px_rgba(245,158,11,0.8)]' : 'w-full bg-white/10'}` }, idx))) })]
            })
        })
    }));
};
const Home = () => {
    const { museums, language, uiLabels: labels } = useContext(AppContext);
    const [searchTerm, setSearchTerm] = useState('');
    const filteredMuseums = museums.filter(m => m.name[language].toLowerCase().includes(searchTerm.toLowerCase()) ||
        m.location[language].toLowerCase().includes(searchTerm.toLowerCase()));
    return (_jsxs("div", {
        className: "pb-20", children: [_jsxs("section", {
            className: "relative h-[85vh] flex items-center justify-center overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0 bg-slate-950", children: [_jsx("div", { className: "absolute top-[-20%] left-[-20%] w-[140%] h-[140%] bg-[radial-gradient(circle_at_50%_50%,rgba(79,70,229,0.1),transparent_50%)] animate-float" }), _jsx("div", { className: "absolute bottom-[-20%] right-[-20%] w-[140%] h-[140%] bg-[radial-gradient(circle_at_50%_50%,rgba(245,158,11,0.05),transparent_50%)] animate-float", style: { animationDelay: '2s' } }), _jsx("div", { className: "absolute top-0 left-0 w-full h-full bg-[url('https://images.unsplash.com/photo-1544967082-d9d37101e950?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80')] bg-cover bg-center opacity-20 mix-blend-overlay" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-slate-950/80 via-slate-950/90 to-slate-950" })] }), _jsxs("div", {
                className: "relative z-10 text-center px-4 max-w-4xl mx-auto -mt-20", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-800/50 border border-slate-700 backdrop-blur-md mb-6 animate-fade-in", children: [_jsx(Sparkles, { size: 16, className: "text-amber-400" }), _jsx("span", { className: "text-slate-300 text-sm font-medium", children: language === 'en' ? 'Explore the Heritage of Bhopal' : 'Explore the Heritage of Bhopal' })] }), _jsx("h1", { className: "text-6xl md:text-8xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-amber-200 via-white to-amber-200 tracking-tighter drop-shadow-2xl animate-pulse-glow", children: "MuseumX" }), _jsx("p", {
                    className: "text-xl md:text-2xl text-slate-300 mb-10 font-light max-w-2xl mx-auto leading-relaxed", children: language === 'en'
                        ? 'Discover the rich heritage, tribal culture, and artistic legacy of the City of Lakes through an immersive digital experience.'
                        : 'Discover the rich heritage, tribal culture, and artistic legacy of the City of Lakes through an immersive digital experience.'
                }), _jsxs("div", { className: "relative max-w-xl mx-auto group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-amber-500 to-amber-700 rounded-full blur opacity-20 group-hover:opacity-40 transition-opacity duration-500" }), _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-y-0 left-0 pl-5 flex items-center pointer-events-none", children: _jsx(Search, { className: "text-slate-400 group-focus-within:text-amber-400 transition-colors" }) }), _jsx("input", { type: "text", placeholder: labels.search, value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full bg-slate-900/80 backdrop-blur-xl border border-slate-700/50 rounded-full py-4 pl-12 pr-6 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500/50 transition-all shadow-xl" })] })] })]
            })]
        }), _jsx(ExhibitionSlider, { museums: museums }), _jsxs("section", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-20", children: [_jsxs("div", { className: "flex items-center gap-4 mb-10", children: [_jsx("div", { className: "w-1.5 h-10 bg-gradient-to-b from-amber-400 to-amber-600 rounded-full" }), _jsx("h2", { className: "text-3xl font-bold text-white", children: labels.explore })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8", children: filteredMuseums.map((museum) => (_jsxs(Link, { to: `/museum/${museum.id}`, className: "group bg-slate-900/50 backdrop-blur-sm rounded-3xl overflow-hidden border border-slate-800 hover:border-amber-500/50 transition-all duration-500 hover:shadow-[0_0_30px_rgba(0,0,0,0.5)] hover:-translate-y-2 flex flex-col h-full relative", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-amber-500/0 via-transparent to-amber-500/0 group-hover:from-amber-500/5 group-hover:to-amber-500/5 transition-colors duration-500" }), _jsxs("div", { className: "relative h-64 overflow-hidden", children: [_jsx("img", { src: museum.image, alt: museum.name[language], className: "w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-slate-900 to-transparent opacity-90" }), _jsxs("div", { className: "absolute bottom-5 left-5 right-5 z-10", children: [_jsx("h3", { className: "text-2xl font-bold text-white mb-2 leading-tight group-hover:text-amber-400 transition-colors", children: museum.name[language] }), _jsxs("div", { className: "flex items-center text-slate-400 text-sm gap-1.5", children: [_jsx(MapPin, { size: 14, className: "text-amber-500" }), _jsx("span", { className: "truncate", children: museum.location[language] })] })] })] }), _jsxs("div", { className: "p-6 pt-2 flex-1 flex flex-col relative z-10", children: [_jsx("p", { className: "text-slate-400 text-sm mb-6 flex-1 leading-relaxed border-b border-slate-800 pb-4", children: museum.shortDescription[language] }), _jsxs("div", { className: "flex items-center justify-between mt-auto", children: [_jsx("div", { className: "flex gap-2", children: museum.features[language].slice(0, 2).map((feature, i) => (_jsx("span", { className: "px-2.5 py-1 bg-slate-800 text-slate-300 text-xs font-medium rounded-lg border border-slate-700", children: feature }, i))) }), _jsx("span", { className: "w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-amber-500 group-hover:bg-amber-500 group-hover:text-slate-900 transition-all duration-300 transform group-hover:rotate-[-45deg]", children: _jsx(ArrowRight, { size: 20 }) })] })] })] }, museum.id))) }), filteredMuseums.length === 0 && (_jsx("div", { className: "text-center py-20 text-slate-500", children: language === 'en' ? 'No museums found matching your search.' : 'No museums found matching your search.' }))] })]
    }));
};
export default Home;
